services:
  - type: web
    name: python-blog
    runtime: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: blog-db
    plan: free
